## U24AI074

### Assignment 1

Q1. You need to complete 4 tasks.
a. Visit https://huggingface.co/datasets/ai4bharat/IndicCorpV2 website and
download the data from your language. Extract all the data.

b. You need to write codes for a sentence tokenizer and word tokenizer. Tokenize
each paragraph into sentences and words. Tokenize each word. Your tokenizer
should tokenize punctuations, URLS, numbers (handle decimals), mail ids, dates.

c. After your data is tokenized, save them into a file or multiple files.

d. Then compute the following corpus statistics:

i. Total number of sentences

ii. Total number of words

iii. Total number of characters

iv. Average Sentence Length (Average number of words per sentence)

v. Average word length (Average number of characters per word)

vi. Type/Token Ratio (TTR) (Total number of unique tokens / Total number of
tokens)

In [1]:
import os
from datasets import load_dataset

os.makedirs("raw_data", exist_ok=True)
print("download started")

ds = load_dataset(
    "ai4bharat/IndicCorpV2", 
    data_files="data/hi-1.txt", 
    split="train", 
    streaming=True
)

count = 0
with open("raw_data/hin_Deva_raw.txt", "w", encoding="utf-8") as f:
    for row in ds:
        text = row["text"].strip()
        if text:
            f.write(text + "\n")
            count += 1
            
            if count >= 520000:
                break

print("Finshed")

download started

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Finshed

In [2]:
import re
import pandas as pd

In [3]:
with open("./raw_data/hin_Deva_raw.txt", "r", encoding="utf-8") as f:   
    text=f.read()

print(text[:500])
print(len(text))

लोगों को बिलों संबंधी सुविधा देना ही उनका काम
इनेलो 1987 में उस वक्त ऐसे ही दोराहे पर खड़ी थी, जब पूर्व उपप्रधानमंत्री देवीलाल ने अपने पुत्र ओमप्रकाश चौटाला को अपना राजनीतिक उत्तराधिकारी घोषित किया था। हालांकि तब पार्टी पर देवीलाल की मजबूत पकड़ के चलते पार्टी टूटने से बच गई थी। 1989 में देवीलाल केन्द्र की राजनीति में सक्रिय हो गए थे और उनके उपप्रधानमंत्री बनने के पश्चात् उनके तीन बेटों जगदीश सिंह, रणजीत सिंह और ओमप्रकाश चौटाला में से रणजीत और ओमप्रकाश के बीच हरियाणा में उनकी राजनीतिक विरासत को ल
152982177

In [4]:
def sentence_tokenize(text):
    sentences=re.split(r"(?<=[।!?॥])\s+|(?<=[a-zA-Z\u0900-\u097F]\.)\s+", text)
    sentences=[s.strip() for s in sentences if s.strip()]
    return sentences
sentences=sentence_tokenize(text)

In [5]:
for i in range(0,15):
    print(sentences[i])

लोगों को बिलों संबंधी सुविधा देना ही उनका काम
इनेलो 1987 में उस वक्त ऐसे ही दोराहे पर खड़ी थी, जब पूर्व उपप्रधानमंत्री देवीलाल ने अपने पुत्र ओमप्रकाश चौटाला को अपना राजनीतिक उत्तराधिकारी घोषित किया था।
हालांकि तब पार्टी पर देवीलाल की मजबूत पकड़ के चलते पार्टी टूटने से बच गई थी।
1989 में देवीलाल केन्द्र की राजनीति में सक्रिय हो गए थे और उनके उपप्रधानमंत्री बनने के पश्चात् उनके तीन बेटों जगदीश सिंह, रणजीत सिंह और ओमप्रकाश चौटाला में से रणजीत और ओमप्रकाश के बीच हरियाणा में उनकी राजनीतिक विरासत को लेकर जंग शुरू हो गई थी।
उन परिस्थितियों में देवीलाल ने कड़ा निर्णय लेते हुए पार्टी की बागडोर ओमप्रकाश चौटाला के हवाले कर दी थी, जिसके बाद रणजीत की बगावत का असर पार्टी, संगठन और उनकी सरकार पर भी पड़ा था।
उस समय रणजीत की नाराजगी के चलते उनके समर्थन में कई कैबिनेट मंत्रियों ने इस्तीफे दे दिए थे किन्तु तब पार्टी सुप्रीमो चौ.
देवीलाल की हरियाणा की जनता पर इतनी मजबूत पकड़ थी कि ओमप्रकाश चौटाला को उत्तराधिकारी बनाने के उनके फैसले का जनता के बीच कोई खास विरोध नहीं हुआ था लेकिन आज स्थिति बिल्कुल विपरीत है।
ओमप्रकाश चौटाला पिछले काफी समय से जेल में हैं और जेल में रहते पार्टी के साथ-साथ परिवार पर भी उनकी पकड़ काफी ढ़ीली हो गई है, इसी कारण उनमें अब देवीलाल जैसा वो सामर्थ्य नजर नहीं आता कि वे अपने फैसलों को बगैर किसी प्रतिरोध के लागू करा सकें।
जहां आई थी तबाही उस घाटी क्षेत्र में खतरा ज्यादा
इसके बाद केंद्र की ओर से प्रदेश सरकार को पीएमजीएसवाई में 200 करोड़ रुपये की राशि उपलब्ध करा दी गई।
भाजपा के मीडिया प्रभारी दिवाकर सिंह ने शनिवार को बताया कि केंद्र ने प्रदेश सरकार को 200 करोड़ रुपये भेजा है।
यह पूछने पर कि इस बड़े मैच से पहले उनकी नींद गायब हुई तो बाबर ने कहा, "हम काफी टूर्नामेंट खेल चुके हैं, हमने चैम्पियंस ट्राफी में भी अच्छा किया था.
हम इसे जितना सरल रखेंगे, उतना ही बेहतर होगा.
इसमें सिर्फ बेसिक्स पर अडिग रहना होगा और साथ ही शांत चित्त बने रहना होगा.
हमारी तैयारी हमारे हाथों में हैं और हमने अपना शत प्रतिशत दिया है.
हमें मैच के दिन अच्छी क्रिकेट खेलने की उम्मीद है."
समाचार एजेंसी 'डीपीए' के अनुसार, उप गृह मंत्री पैट्रीकियो रोसेंडे ने कहा कि 76 लोगों के मरने की पुष्टि हो चुकी है।
पिछले कई सालों से हमने इतना बड़ा हादसा नहीं देखा।

In [6]:
token_pattern=re.compile(
    r'https?://\S+|www\.\S+\.\S+' #url
    r'|([\w\.-]+@[\w\.-]+\.\w+)' #mail
    r'|(\d{1,2}[-/]\d{1,2}[-/]\d{2,4})' #dates
    r'|(\d+\.\d+)' #decimal
    r'|(\d+)' #Integers
    r'|([a-zA-Z\u0900-\u0963\u0966-\u097F]+)' #English or Hindi words
    r'|([^\w\s])' #Punctuations

)


def word_tokenize(sentence):
    tokens=[]
    for match in token_pattern.finditer(sentence):
        tokens.append(match.group())

    return tokens

test_text=sentences[0]
print(f"{word_tokenize(test_text)}")

['लोगों', 'को', 'बिलों', 'संबंधी', 'सुविधा', 'देना', 'ही', 'उनका', 'काम', 'इनेलो', '1987', 'में', 'उस', 'वक्त', 'ऐसे', 'ही', 'दोराहे', 'पर', 'खड़ी', 'थी', ',', 'जब', 'पूर्व', 'उपप्रधानमंत्री', 'देवीलाल', 'ने', 'अपने', 'पुत्र', 'ओमप्रकाश', 'चौटाला', 'को', 'अपना', 'राजनीतिक', 'उत्तराधिकारी', 'घोषित', 'किया', 'था', '।']

In [7]:
df=pd.DataFrame({
    "sentence":sentences
})
df.head()

                                            sentence
0  लोगों को बिलों संबंधी सुविधा देना ही उनका काम\...
1  हालांकि तब पार्टी पर देवीलाल की मजबूत पकड़ के ...
2  1989 में देवीलाल केन्द्र की राजनीति में सक्रिय...
3  उन परिस्थितियों में देवीलाल ने कड़ा निर्णय लेत...
4  उस समय रणजीत की नाराजगी के चलते उनके समर्थन मे...

In [8]:
df["tokens"]=df["sentence"].apply(word_tokenize)
df["token_count"]=df["tokens"].apply(len)
df.head()

,sentence,tokens,token_count
0,लोगों को बिलों संबंधी सुविधा देना ही उनका काम\...,"[लोगों, को, बिलों, संबंधी, सुविधा, देना, ही, उ...",38
1,हालांकि तब पार्टी पर देवीलाल की मजबूत पकड़ के ...,"[हालांकि, तब, पार्टी, पर, देवीलाल, की, मजबूत, ...",17
2,1989 में देवीलाल केन्द्र की राजनीति में सक्रिय...,"[1989, में, देवीलाल, केन्द्र, की, राजनीति, में...",48
3,उन परिस्थितियों में देवीलाल ने कड़ा निर्णय लेत...,"[उन, परिस्थितियों, में, देवीलाल, ने, कड़ा, निर...",38
4,उस समय रणजीत की नाराजगी के चलते उनके समर्थन मे...,"[उस, समय, रणजीत, की, नाराजगी, के, चलते, उनके, ...",24

In [9]:
import os

In [10]:
os.makedirs("tokenized_output", exist_ok=True)
df.to_parquet(
    "tokenized_output/hin_corpus_tokenized.parquet",
    index=False,
    engine="pyarrow",
    compression="snappy"
)

In [11]:
df=pd.read_parquet(
    "tokenized_output/hin_corpus_tokenized.parquet"
)

df.head()

,sentence,tokens,token_count
0,लोगों को बिलों संबंधी सुविधा देना ही उनका काम\...,"[लोगों, को, बिलों, संबंधी, सुविधा, देना, ही, उ...",38
1,हालांकि तब पार्टी पर देवीलाल की मजबूत पकड़ के ...,"[हालांकि, तब, पार्टी, पर, देवीलाल, की, मजबूत, ...",17
2,1989 में देवीलाल केन्द्र की राजनीति में सक्रिय...,"[1989, में, देवीलाल, केन्द्र, की, राजनीति, में...",48
3,उन परिस्थितियों में देवीलाल ने कड़ा निर्णय लेत...,"[उन, परिस्थितियों, में, देवीलाल, ने, कड़ा, निर...",38
4,उस समय रणजीत की नाराजगी के चलते उनके समर्थन मे...,"[उस, समय, रणजीत, की, नाराजगी, के, चलते, उनके, ...",24

In [12]:
all_token_flat=[
    token
    for token_list in df["tokens"]
    for token in token_list
]

In [13]:
total_sentences=len(df)

In [14]:
total_tokens=df['token_count'].sum()

In [15]:
total_characters=sum(len(token) for token in all_token_flat)

In [16]:
avg_sentence_len=total_tokens/total_sentences if total_sentences>0 else 0
avg_word_len=total_characters/total_tokens if total_tokens>0 else 0

In [17]:
unique_tokens=len(set(all_token_flat))
ttr=unique_tokens/total_tokens if total_tokens>0 else 0

In [18]:
print(f"i.   Total number of sentences: {total_sentences:,}")
print(f"ii.  Total number of words: {total_tokens:,}")
print(f"iii. Total number of characters: {total_characters:,}")
print(f"iv.  Average Sentence Length: {avg_sentence_len:.2f} words/sentence")
print(f"v.   Average word length: {avg_word_len:.2f} characters/word")
print(f"vi.  Type/Token Ratio (TTR): {ttr:.6f} ({unique_tokens:,} unique / {total_tokens:,} total)")

i.   Total number of sentences: 1,496,811
ii.  Total number of words: 33,151,611
iii. Total number of characters: 122,934,958
iv.  Average Sentence Length: 22.15 words/sentence
v.   Average word length: 3.71 characters/word
vi.  Type/Token Ratio (TTR): 0.011857 (393,078 unique / 33,151,611 total)